mybatis:
  mapperLocations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
